version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["/app/main", "api"]
    environment:
      - MONGO_DSN=mongodb://mongo:27017
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["/app/main", "worker"]
    environment:
      - MONGO_DSN=mongodb://mongo:27017
    ports:
      - "8081:8081"
    depends_on:
      - mongo

  mongo:
    image: mongodb/mongodb-community-server:latest
    container_name: mongo
    ports:
      - "27017:27017"